# This file contains values from Cookiecutter
# Made with https://gitlab.com/galactipy/galactipy

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  repo_name: "{{ cookiecutter.repo_name }}"
  package_name: "{{ cookiecutter.package_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  copyright: "{{ cookiecutter.copyright }}"
  maintainer: "{{ cookiecutter.maintainer }}"
  scm_platform: "{{ cookiecutter.scm_platform }}"
  scm_namespace: "{{ cookiecutter.scm_namespace }}"
  email: "{{ cookiecutter.email }}"
  licence: "{{ cookiecutter.licence }}"
  minimal_python_version: "{{ cookiecutter.minimal_python_version }}"
  line_length: {{ cookiecutter.line_length }}
  docstring_style: "{{ cookiecutter.docstring_style }}"
  docstring_length: {{ cookiecutter.docstring_length }}
  commit_convention: "{{ cookiecutter.commit_convention }}"
  use_bdd: {{ cookiecutter.use_bdd }}
  coverage_service: "{{ cookiecutter.coverage_service }}"
  create_docker: {{ cookiecutter.create_docker }}
  app_type: "{{ cookiecutter.app_type }}"
